#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -r /tmp/sxhkd.log &

# modified
xsetroot -cursor_name left_ptr &
xrdb -load .Xresources &
bash "${HOME}"/.fehbg &
bash "${HOME}"/.config/polybar/launch.sh &
picom --experimental-backends &
/usr/lib/polkit-kde-authentication-agent-1 &
dunst &
if [ -z "$(pgrep -f /home/wraith/.node_modules/bin/gt)" ];then
    /home/wraith/.node_modules/bin/gt --dns-type "tls" --dns-server "8622a7.dns.nextdns.io" &
fi

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# edited
bspc config focus_follows_pointer    true
bspc config ignore_ewmh_focus        true


# colors
bspc config focused_border_color  "#aecc00"
bspc config normal_border_color   "#62578c"
bspc config active_border_color   "#ff89b5"

# mouse tweaks
bspc config pointer_action1          move
bspc config pointer_action2          resize_side
bspc config pointer_action3          resize_corner
