return require("packer").startup(
	function()
		-- packer can manage itself
		use 'wbthomason/packer.nvim'
		use 'neovim/nvim-lspconfig'
		use 'nvim-lua/lsp-status.nvim'
		use 'nvim-lua/lsp_extensions.nvim'
		use 'nvim-lua/completion-nvim'
		use 'rishabhrd/nvim-lsputils'
		use 'kosayoda/nvim-lightbulb'
		use 'onsails/lspkind-nvim'
		use 'ray-x/lsp_signature.nvim'
		use 'nanotee/sqls.nvim'
		use 'jubnzv/virtual-types.nvim'
		use 'npxbr/glow.nvim'
		use 'nvim-treesitter/nvim-treesitter'
		use 'nvim-telescope/telescope.nvim'
		use 'nvim-lua/popup.nvim'
		use 'nvim-lua/plenary.nvim'
		use 'norcalli/nvim-colorizer.lua'
		use 'norcalli/nvim-base16.lua'
		use 'kyazdani42/nvim-web-devicons'
		use 'akinsho/nvim-bufferline.lua'
		use 'glepnir/galaxyline.nvim'
		use 'glepnir/indent-guides.nvim'
		use 'kyazdani42/nvim-tree.lua'
		use 'lewis6991/gitsigns.nvim'
		use 'b3nj5m1n/kommentary'
		use 'xuyuanp/scrollbar.nvim'
		use 'tpope/vim-surround'
		use 'ryanoasis/vim-devicons'
		use 'acksld/nvim-whichkey-setup.lua'
		use 'liuchengxu/vim-which-key'
		use 'windwp/nvim-autopairs'
		-- theme
		use 'glepnir/zephyr-nvim'
	end
)
